---
- name: "Nettoyage complet du cluster Kubernetes"
  hosts: all
  become: true
  gather_facts: false
  
  tasks:
    - name: "Reset du cluster Kubernetes"
      shell: kubeadm reset -f
      ignore_errors: true

    - name: "Arrêt des services Kubernetes"
      systemd:
        name: "{{ item }}"
        state: stopped
      loop:
        - kubelet
        - containerd
      ignore_errors: true

    - name: "Suppression des fichiers de configuration Kubernetes"
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/kubernetes/
        - /var/lib/kubelet/
        - /var/lib/etcd/
        - /etc/cni/net.d/
        - /home/ubuntu/.kube/
        - /root/.kube/

    - name: "Suppression des interfaces réseau"
      shell: |
        ip link delete flannel.1 2>/dev/null || true
        ip link delete cni0 2>/dev/null || true
        ip link delete docker0 2>/dev/null || true
      ignore_errors: true

    - name: "Nettoyage des règles iptables"
      shell: |
        iptables -F
        iptables -t nat -F
        iptables -t mangle -F
        iptables -X
      ignore_errors: true

    - name: "Redémarrage des services réseau"
      systemd:
        name: "{{ item }}"
        state: restarted
      loop:
        - containerd
        - kubelet
      ignore_errors: true

    - name: "Vérification du nettoyage"
      shell: |
        kubectl version --client || echo "kubectl non accessible (normal après nettoyage)"
        docker ps || echo "Docker non accessible"
      register: cleanup_status
      ignore_errors: true

    - name: "Affichage du statut de nettoyage"
      debug:
        var: cleanup_status.stdout_lines