models:
  - title: "Ollama - Mistral (remote)"
    provider: "ollama"
    model: "mistral"
    api_base: "http://192.168.1.72:11434"
    remote: true
  - title: "Ollama - CodeLlama (remote)"
    provider: "ollama"
    model: "codellama"
    api_base: "http://192.168.1.72:11434"
    remote: true