models:
  - title: "Ollama - Mistral"
    provider: "ollama"
    model: "mistral"
    base_url: "http://192.168.1.72:11434"
    remote: true

  - title: "Ollama - CodeLlama"
    provider: "ollama"
    model: "codellama"
    base_url: "http://192.168.1.72:11434"
    remote: true