version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - /volume1/ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=3600
      - OLLAMA_NUM_THREADS=4
      - OLLAMA_HOST=0.0.0.0