---
- name: "Installation des composants Kubernetes"
  tags: kubernetes
  block:
    - name: "Téléchargement et installation de la clé GPG Kubernetes"
      shell: |
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: "Ajout du dépôt Kubernetes"
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: kubernetes

    - name: "Mise à jour du cache APT"
      apt:
        update_cache: true

    - name: "Installation de kubelet, kubeadm et kubectl"
      apt:
        name:
          - kubelet
          - kubeadm  
          - kubectl
        state: present
        update_cache: true

    - name: "Verrouillage des versions Kubernetes"
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: "Activation et démarrage de kubelet"
      systemd:
        name: kubelet
        enabled: true
        state: started