---
- name: "Installation des composants Kubernetes"
  tags: kubernetes
  block:
    - name: "Ajout de la clé GPG Kubernetes"
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
        state: present

    - name: "Ajout du dépôt Kubernetes"
      apt_repository:
        repo: "deb https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
        state: present
        filename: kubernetes

    - name: "Mise à jour du cache APT"
      apt:
        update_cache: true

    - name: "Installation de kubelet, kubeadm et kubectl"
      apt:
        name:
          - kubelet
          - kubeadm  
          - kubectl
        state: present
        update_cache: true

    - name: "Verrouillage des versions Kubernetes"
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: "Activation et démarrage de kubelet"
      systemd:
        name: kubelet
        enabled: true
        state: started