---
- name: "Configuration des nœuds workers"
  block:
    - name: "Vérification si le nœud a déjà rejoint le cluster"
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf_stat

    - name: "Récupération de la commande de jointure depuis le master"
      shell: kubeadm token create --print-join-command
      register: join_command_result
      delegate_to: "{{ groups['masters'][0] }}"
      run_once: true
      when: not kubelet_conf_stat.stat.exists

    - name: "Jointure du nœud au cluster"
      shell: "{{ join_command_result.stdout }}"
      when: 
        - not kubelet_conf_stat.stat.exists
        - join_command_result is defined

    - name: "Vérification du statut du nœud"
      shell: systemctl is-active kubelet
      register: kubelet_status
      failed_when: false

    - name: "Redémarrage de kubelet si nécessaire"
      systemd:
        name: kubelet
        state: restarted
      when: kubelet_status.stdout != "active"