---
- name: "Configuration commune pour tous les nœuds"
  tags: common
  block:
    - name: "Désactivation du swap"
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      when: swap_disabled

    - name: "Installation des packages requis"
      apt:
        name: "{{ common_packages }}"
        state: present
        update_cache: yes

    - name: "Ajout des modules kernel requis"
      modprobe:
        name: "{{ item }}"
        state: present
      loop: "{{ kernel_modules }}"

    - name: "Configuration persistante des modules kernel"
      copy:
        dest: /etc/modules-load.d/k8s.conf
        content: |
          br_netfilter
          overlay

    - name: "Configuration sysctl pour Kubernetes"
      copy:
        dest: /etc/sysctl.d/k8s.conf
        content: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: "Application des paramètres sysctl"
      shell: sysctl --system

    - name: "Désactivation du firewall UFW"
      ufw:
        state: disabled
      when: firewall_disabled

    - name: "Ajout du repository Kubernetes"
      shell: |
        # Nettoyage préalable
        rm -f /etc/apt/sources.list.d/kubernetes.list
        rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg
        
        # Création répertoire
        mkdir -p /etc/apt/keyrings
        
        # Téléchargement avec retry et timeout (URL directe CDN)
        for i in {1..3}; do
          if curl -fsSL --connect-timeout 30 --max-time 60 \
             "https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v1.28/deb/Release.key" \
             | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg; then
            chmod 644 /etc/apt/keyrings/kubernetes-apt-keyring.gpg
            echo "Clé GPG installée avec succès (tentative $i)"
            break
          else
            echo "Tentative $i échouée, retry dans 10s..."
            sleep 10
          fi
        done
        
        # Ajout du repository
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

    - name: "Mise à jour du cache APT après ajout du repo"
      apt:
        update_cache: yes