---
- name: "Configuration du nœud master"
  block:
    - name: "Vérification si le cluster est déjà initialisé"
      stat:
        path: /etc/kubernetes/admin.conf
      register: kubeconfig_stat

    - name: "Initialisation du cluster Kubernetes"
      shell: |
        kubeadm init \
          --pod-network-cidr={{ pod_network_cidr }} \
          --service-cidr={{ service_network_cidr }} \
          --apiserver-advertise-address={{ ansible_default_ipv4.address }} \
          --node-name={{ inventory_hostname }}
      register: kubeadm_init
      when: not kubeconfig_stat.stat.exists

    - name: "Affichage de la sortie de kubeadm init"
      debug:
        var: kubeadm_init.stdout_lines
      when: kubeadm_init is defined and kubeadm_init.changed

    - name: "Création du répertoire .kube pour l'utilisateur hocine"
      file:
        path: /home/hocine/.kube
        state: directory
        owner: hocine
        group: hocine
        mode: '0755'

    - name: "Copie du fichier de configuration kubectl"
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/hocine/.kube/config
        owner: hocine
        group: hocine
        mode: '0644'
        remote_src: true

    - name: "Copie du fichier de configuration kubectl pour root"
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /root/.kube/config
        owner: root
        group: root
        mode: '0644'
        remote_src: true

    - name: "Création du répertoire .kube pour root"
      file:
        path: /root/.kube
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: "Installation du plugin réseau Flannel"
      shell: kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: not kubeconfig_stat.stat.exists

    - name: "Génération du token de jointure"
      shell: kubeadm token create --print-join-command
      register: join_command
      when: not kubeconfig_stat.stat.exists

    - name: "Sauvegarde de la commande de jointure"
      set_fact:
        kubernetes_join_command: "{{ join_command.stdout }}"
      when: join_command is defined

    - name: "Attente que tous les nœuds soient prêts"
      shell: kubectl get nodes --no-headers | grep -v NotReady | wc -l
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: ready_nodes
      until: ready_nodes.stdout|int >= groups['all']|length
      retries: 30
      delay: 10

    - name: "Déploiement du Kubernetes Dashboard"
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v2.7.0/aio/deploy/recommended.yaml
        # Modification du service pour NodePort
        kubectl patch svc kubernetes-dashboard -n kubernetes-dashboard -p '{"spec":{"type":"NodePort","ports":[{"port":443,"targetPort":8443,"nodePort":30443}]}}'
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: not kubeconfig_stat.stat.exists

    - name: "Création de l'utilisateur admin pour le dashboard"
      copy:
        dest: /tmp/dashboard-admin.yaml
        content: |
          apiVersion: v1
          kind: ServiceAccount
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
          ---
          apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: admin-user
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: cluster-admin
          subjects:
          - kind: ServiceAccount
            name: admin-user
            namespace: kubernetes-dashboard
          ---
          apiVersion: v1
          kind: Secret
          metadata:
            name: admin-user
            namespace: kubernetes-dashboard
            annotations:
              kubernetes.io/service-account.name: "admin-user"   
          type: kubernetes.io/service-account-token
      when: not kubeconfig_stat.stat.exists

    - name: "Application de la configuration admin dashboard"
      shell: kubectl apply -f /tmp/dashboard-admin.yaml
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      when: not kubeconfig_stat.stat.exists

    - name: "Attente du déploiement du dashboard"
      shell: kubectl get pods -n kubernetes-dashboard --no-headers | grep Running | wc -l
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: dashboard_pods
      until: dashboard_pods.stdout|int >= 2
      retries: 20
      delay: 15
      when: not kubeconfig_stat.stat.exists